# Generated by Django 6.1 on 2026-08-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphaclinic', '0002_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labtests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discription', models.TextField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
