# Generated by Django 6.1 on 2026-08-20 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphaclinic', '0003_labtests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor',
            new_name='doctor_name',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='patient_name',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alphaclinic.appointment')),
            ],
        ),
    ]
