# Generated by Django 6.1 on 2026-08-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphaclinic', '0004_rename_doctor_appointment_doctor_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor_name',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_name',
            new_name='patient',
        ),
        migrations.AddField(
            model_name='appointment',
            name='lab_tests',
            field=models.ManyToManyField(blank=True, to='alphaclinic.labtests'),
        ),
    ]
