# Generated by Django 6.1 on 2026-08-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphaclinic', '0006_rename_appointment_id_bill_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bill',
            name='discount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bill',
            name='doctor_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='bill',
            name='medicine_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
