# Generated by Django 6.1 on 2026-08-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.TextField(max_length=255, unique=True)),
                ('driver_name', models.CharField(max_length=255)),
                ('ambulance_type', models.CharField(max_length=255)),
                ('ambulance_status', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('Maintenance', 'Maintenance')], default='Available', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
