# Generated by Django 6.1 on 2026-08-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='vehicle_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
