# Generated by Django 6.1 on 2026-08-20 07:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0002_alter_ambulance_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency_call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255, null=True)),
                ('priority_status', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('request_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('request_status', models.CharField(choices=[('pending', 'pending'), ('dispatched', 'dispatched'), ('completed', 'completed')], default='pending', max_length=20)),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.ambulance')),
            ],
        ),
    ]
